image: node:latest

variables:
  PUBLIC_URL: /OurHouse

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run build      # Build for prod

  artifacts:
    paths:
    - public

  only:
    - main
