image: node:latest

variables:
  PUBLIC_URL: /OurHouse

cache:
  paths:
  - frontend/node_modules
  - frontend/.next/cache

pages:
  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - npm run export

  artifacts:
    paths:
    - frontend/out
    - "frontend/public/"

  only:
    - main
