image: node:latest

variables:
  PUBLIC_URL: /OurHouse

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - frontend/node_modules
  - frontend/.next

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run-script build && npm run-script start
    - rm -rf public/*
    - mv out/* public

  artifacts:
    paths:
    - frontend/public

  only:
    - main
