image: node:latest

variables:
  PUBLIC_URL: /OurHouse

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - mv frontend/public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build frontend/public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
    - frontend/public

  only:
    - main
