image: node

variables:
  PUBLIC_URL: /OurHouse

cache:
  key: ${CI_COMMIT_REF_SLUG}
  paths:
  - frontend/node_modules
  - frontend/.next/cache

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run-script build && npm run-script export
    - cd ..
    - mv public _public
    - mv build public

  artifacts:
    paths:
    - frontend/public

  only:
    - main
