image: node:latest

variables:
  PUBLIC_URL: /OurHouse

cache:
  paths:
  - node_modules

stages:
  - deploy

pages:
  stage: deploy

  script:
    - cd frontend
    - npm install        # Install all dependencies
    - npm run build      # Build for prod
    - mv public _public  # CRA and gitlab pages both use the public folder. Only do this in a build pipeline.
    - mv build public    # Move build files to public dir for Gitlab Pages

  artifacts:
    paths:
    - frontend/public
    - frontend/.next
    - frontend/components
    - frontend/pages
    - frontend/resources
    - frontend/styles

  only:
    - main
