# The Docker image that will be used to build your app
image: node:latest

cache:
  paths:
    - frontend/.next
    - frontend/node_modules

# Functions that should be executed before the build script is run
before_script:
  - cd frontend
  - npm ci
pages:
  script:
    - next build
    - next export
    - mv out/* public
    - rm -rf out
  artifacts:
    paths:
      # The folder that contains the files to be exposed at the Page URL
      - frontend/public

  only:
    - main
